### PR TITLE
feat(spec): Report all expand errors

### PR DESCRIPTION
**Pull request by erezrokah**
#### Summary

Related to https://github.com/cloudquery/plugin-sdk/issues/613 and https://github.com/cloudquery/plugin-sdk/issues/480.
This PR refactors the code to use built in `os.Expand` and avoids using multiple regular expressions.
It also reports all relevant errors instead of just the last one

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by hermanschaaf — APPROVED** [review]
LGTM, nice one! Maybe just worth noting that there is a slight change in behavior: I believe previously we didn't expand `$VAR` but now we do, because `os.Expand` accepts both `$VAR` and `${VAR}`

**Review by yevgenypats — COMMENTED** [review]
Nice one! Per @hermanschaaf comment maybe we do want to keep the regex to expand stuff as we have more control over it as I feel we might go back and forth with this code as before it was `os.Expand` and then I needed some more control so I falled back to regex. It's not that `os.Expand` saves alot of code in that case?

**Comment by erezrokah** [comment]
> Nice one! Per @hermanschaaf comment maybe we do want to keep the regex to expand stuff as we have more control over it as I feel we might go back and forth with this code as before it was `os.Expand` and then I needed some more control so I falled back to regex. It's not that `os.Expand` saves alot of code in that case?

I think we used to support both `$` and `${}` as we used `os.ExpandEnv`. I think maybe you're referring to `os.ExpandEnv` lack of control? See https://github.com/cloudquery/plugin-sdk/pull/499/files#diff-12fc83214927c910b85cf4b5e8ec7e26de428fd7293767e4a807bfdcab8f042bL41

I think this mostly saves the usage of RegExp to re-implement code that's already available in the standard lib

**Comment by yevgenypats** [comment]
> 

I would actually want to rollback to regex as it was already implemented so it doesn't really save us from implementing it again. The reason is because if we ever want to add additional find/replace capability the code is already there and we wont need to go back and forth. basically the version of the code right now is a more advanced so I don't see a reason to move us back and then move here again if we will need it.

**Comment by erezrokah** [comment]
> basically the version of the code right now is a more advanced so I don't see a reason to move us back

Can you explain how the current code is more advanced and how this is a step back?
To add more functionality with the current code one would need write a new Regex (which is error prone) + mostly copy paste a new `expand*` function (and if we want multiple errors report those separately). 
With the new version the expand logic is the same for all cases, and adding new functionality will be in a single place under the same function. Seems like `os.Expand` exists for this use case of providing custom logic when expanding $ placeholders.

If we ever want to do more transformations on the config. it will probably best not to use regular expressions, and process the YAML object to avoid things like https://github.com/cloudquery/plugin-sdk/issues/613.

Regardless I don't think it's high priority so I'll close this PR and we can re-visit if we ever add new functionality

**Pull request closed without merging**
