### PR TITLE
fix: Add GetFlatTableList helper

### PR DESCRIPTION
**Pull request by shimonp21**
#### Summary

Required to fix DeleteStale bug.

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by yevgenypats — CHANGES_REQUESTED** [review]
There is already such function here - https://github.com/cloudquery/plugin-sdk/blob/main/schema/table.go#L68

**Comment by disq** [comment]
Why not recurse in the DeleteStale call? Could even make an intermediary fn that creates larger batches (take a batch, iterate given schema.Tables, add to the batch and return, without SendBatch... so that multiple levels of tables can be batched)

**Comment by erezrokah** [comment]
> There is already such function here - https://github.com/cloudquery/plugin-sdk/blob/main/schema/table.go#L68

And also `GlobMatch` with `*` should work? https://github.com/cloudquery/plugin-sdk/blob/c8c824d0c1842e6b85a6e0d4e0e4102dc1a5ab50/schema/table.go#L111

**Comment by shimonp21** [comment]
Closing this one :)

**Pull request closed without merging**
