### PR TITLE
chore: Refactor some goroutine-related code

### PR DESCRIPTION
**Pull request by hermanschaaf**
Refactoring some code that I initially thought had a bug, but actually didn't. 😄

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]

**Review by disq — APPROVED** [review]
🤦

**Review by yevgenypats — CHANGES_REQUESTED** [review]
I can see how this is a potential improvement but Im not sure there was any race condition here.  the `return` statement would only be called after `close(resources)` would be called and this would only happen after `syncErr` is called so Im requesting changes mostly for a discussion as this can also work but I dont think there was any bug before that.

**Comment by hermanschaaf** [comment]
@yevgenypats Ah, you're absolutely right. I spent too much time staring at this code today, beginning to see bugs where there aren't any 😅 Yeah, looks like there was no bug here, because the deferred closing should mean the outer function always finishes after the variable was already set by the inner goroutine.

Happy to close this, but maybe for future readers this updated version requires a bit less thinking to understand, so I'll leave it up to you whether you think it's an improvement or not. Marking the PR as `chore` in any case.

**Comment by yevgenypats** [comment]
I think in that case let's close it for now given we don't want to touch something that works especially around tricky areas to avoid introducing new bugs :) .

**Pull request closed without merging**
