### PR TITLE
fix(caser): ToSnake does not replace spaces with _

### LINKED ISSUE #728: bug(caser): ToSnake does not replace spaces with `_`
See https://github.com/cloudquery/cloudquery/pull/8728#discussion_r1130874669

### PR DESCRIPTION
**Pull request by ankur0904**
#### Summary

This PR fixes #728 

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by erezrokah — COMMENTED** [review]
Thanks for the PR @ankur0904, do you mind adding some unit tests to it? There's a `caser/caser_test.go` file you can use

**Comment by ankur0904** [comment]
@erezrokah I will add unit test.

**Comment by ankur0904** [comment]
@erezrokah 
If I am adding this `{Camel: "Test Space", Snake: "test_space"}` in `Test_ToSnake` case. Then test got fail 

```
                Error:          Not equal: 
                                expected: "test_space"
                                actual  : "test__space"
```
After observing I come to know when I remove this `word = strings.ReplaceAll(word, " ", "_")` line from `caser.go` file  the error become 
```                Error:          Not equal: 
                                expected: "test_space"
                                actual  : "test _space"
```
According to my observation 
`word = strings.ReplaceAll(word, " ", "")` should be added to `caser.go` this will passing the test case.
```
PASS
ok      github.com/cloudquery/plugin-sdk/v4/caser       0.012s
```

**Comment by ankur0904** [comment]
@erezrokah What are your thoughts?

**Comment by erezrokah** [comment]
> @erezrokah What are your thoughts?

Hi @ankur0904 thank you for looking into it, will that solution work for the following test `{Camel: "Hello Wor ld", Snake: "hello_wor_ld"}`?

I think we might need to first replace spaces on the entire string, then split the words, WDYT?

You can also use https://textedit.tools/snakecase to test

**Comment by ankur0904** [comment]
@erezrokah You are absolutely right `{Camel: "Hello Wor ld", Snake: "hello_wor_ld"}` gives the `error`.

**Comment by ankur0904** [comment]
@erezrokah You are absolutely right `{Camel: "Hello Wor ld", Snake: "hello_wor_ld"}` gives the `error`.

**Comment by ankur0904** [comment]
@erezrokah I have updated the code, in this code I first replace spaces on the entire string then if there is `__` then replace it with `_`. And also added some additional corner cases like e.g. **leading trailing spaces** ` h e l l o`, `h e l l o `, ` h e l l o `

Unit test I added 
```
{Camel: "Hello World", Snake: "hello_world"},
{Camel: "Hello Wor ld", Snake: "hello_wor_ld"},
{Camel: "H e l l o", Snake: "h_e_l_l_o"},
{Camel: "H e l l o ", Snake: "h_e_l_l_o"},
{Camel: " H e l l o", Snake: "h_e_l_l_o"},
{Camel: " H e l l o ", Snake: "h_e_l_l_o"},
```
After running 
```
$ go test
PASS
ok      github.com/cloudquery/plugin-sdk/v4/caser       0.006s
```

**Comment by erezrokah** [comment]
Thanks for following up @ankur0904, looks better but I think it's missing `{Camel: "Hello     World", Snake: "hello_wor_ld"},` (see the multiple spaces).

**Comment by ankur0904** [comment]
@erezrokah Apologize, I have forgotten to mention that.

**Comment by erezrokah** [comment]
> @erezrokah Does anything else we need to change?

Sorry for the late reply. I missed your last commit. I'll take a look tomorrow.

**Comment by ankur0904** [comment]
@erezrokah 

> > @erezrokah Does anything else we need to change?
> 
> Sorry for the late reply. I missed your last commit. I'll take a look tomorrow.

Can this PR be merged?

**Comment by erezrokah** [comment]
> Can this PR be merged?

Hi @ankur0904, let me look at this again. I think this could be simplified to replace the spaces once before splitting the words.

**Comment by ankur0904** [comment]
@erezrokah Should I need to change the code?

**Comment by erezrokah** [comment]
> @erezrokah Should I need to change the code?

Not yet, I'll comment on the PR if that's needed

**Comment by ankur0904** [comment]
@erezrokah OK

**Comment by erezrokah** [comment]
Hi @ankur0904 I opened https://github.com/cloudquery/plugin-sdk/pull/1148 as a draft with a different approach to get rid of the spaces. I think that's more consistent with the current code (doesn't use regular expressions). Please let me know what you think

**Comment by ankur0904** [comment]
@erezrokah #1148 That looks fine and more consistent.

**Comment by candiduslynx** [comment]
Closing, as https://github.com/cloudquery/plugin-sdk/pull/1198 was released as part of `v4.6.4`

**Pull request closed without merging**
