### PR TITLE
feat: Enable Custom Validators

### PR DESCRIPTION
**Pull request by bbernays**
#### Summary

Enable each individual plugin to pass in any and all additional validator functions they want...

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by bbernays** [comment]
> Nice, maybe you can share a PR that uses this?

I am working on one now in the AWS plugin to check for the Tags issue we just solved... https://github.com/cloudquery/cloudquery/pull/7621

**Review by candiduslynx — APPROVED** [review]

**Review by disq — APPROVED** [review]

**Comment by bbernays** [comment]
@erezrokah The initial pr for utilizing this [functionality is up](https://github.com/cloudquery/cloudquery/pull/7651)... It already found 5 issues...

**Review by hermanschaaf — APPROVED** [review]
I'd probably define the Validator function signature as a type, but it's a minor nit 👍

**Review by yevgenypats — CHANGES_REQUESTED** [review]
Looks good. Few thoughts on the validator `interface`

`func(t *testing.T, table *schema.Table, resources *schema.Resource)`

This way the SDK can do the same loop instead of the validator doing the loop again. Unless there is a need for the validator to have access to all tables but I feel it has those when it is calling the test anyway so feel a bit redundant.

Nit: per Herman comment type for the func would be nice.

**Comment by bbernays** [comment]
> Looks good. Few thoughts on the validator `interface`
> 
> `func(t *testing.T, table *schema.Table, resources *schema.Resource)`
> 
> This way the SDK can do the same loop instead of the validator doing the loop again. Unless there is a need for the validator to have access to all tables but I feel it has those when it is calling the test anyway so feel a bit redundant.

I wanted to give the validator access to  all of the tables so that it could validate/ensure consistency across multiple tables... I thought that the hit for performance is negligible...

 
> Nit: per Herman comment type for the func would be nice.

 will look into this

**Comment by yevgenypats** [comment]
> > Looks good. Few thoughts on the validator `interface`
> > `func(t *testing.T, table *schema.Table, resources *schema.Resource)`
> > This way the SDK can do the same loop instead of the validator doing the loop again. Unless there is a need for the validator to have access to all tables but I feel it has those when it is calling the test anyway so feel a bit redundant.
> 
> I wanted to give the validator access to all of the tables so that it could validate/ensure consistency across multiple tables... I thought that the hit for performance is negligible...
> 
> > Nit: per Herman comment type for the func would be nice.
> 
> will look into this

But the validator already have access to all the tables because 

> > Looks good. Few thoughts on the validator `interface`
> > `func(t *testing.T, table *schema.Table, resources *schema.Resource)`
> > This way the SDK can do the same loop instead of the validator doing the loop again. Unless there is a need for the validator to have access to all tables but I feel it has those when it is calling the test anyway so feel a bit redundant.
> 
> I wanted to give the validator access to all of the tables so that it could validate/ensure consistency across multiple tables... I thought that the hit for performance is negligible...
> 
> > Nit: per Herman comment type for the func would be nice.
> 
> will look into this

But the validator already has in some sense access to all the tables. Anyway, if we want to pass the whole context to the validator, I think it makes sense but then let's just use the `Plugin` as a whole?

**Review by candiduslynx — APPROVED** [review]

**Review by yevgenypats — APPROVED** [review]

**Pull request merged**
