### PR TITLE
feat(schema): Add schema.TypeTimeInterval

### PR DESCRIPTION
**Pull request by candiduslynx**
#### Summary

Add duration column type for #178 

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by yevgenypats — CHANGES_REQUESTED** [review]
Looks good. One question - maybe we should call it interval? i.e stick to postgresql types? or at least be consistent with one db? as in the json when it is being sent over the wire it is string anyway.

**Review by hermanschaaf — APPROVED** [review]
LGTM :+1: 

Let's mark it as a breaking change though, because destination plugins will need to explicitly handle this new type.

**Comment by yevgenypats** [comment]
> LGTM 👍
> 
> Let's mark it as a breaking change though, because destination plugins will need to explicitly handle this new type.

I think for destination plugin we need to always default to text as this field can contain anything and we shouldn't break destinations every-time we support new field in CQ.

So I wouldn't mark it as breaking even it will break:) maybe just follow-up PR with the right behaviour to default to text?

**Comment by candiduslynx** [comment]
Now it'll be treated as `int64` -> `schema.TypeInt`, so IDK if that's a good idea to convert this to text.

As for the interval - will do

**Review by yevgenypats — APPROVED** [review]

**Pull request merged**
