### PR TITLE
fix: Use Go memory allocator for arrow

### PR DESCRIPTION
**Pull request by yevgenypats**
Following this short discussion - https://github.com/apache/arrow/issues/35232

It seems we don't really need to use Retain/Release outside the arrow library. We can always bring this back in the future if we would like to experiment if this brings better memory performance then the default go allocator.

### CODE REVIEW

**Comment by candiduslynx** [comment]
So, we should update the plugin code as well? (Stop using release with this update?)

**Comment by yevgenypats** [comment]
> So, we should update the plugin code as well? (Stop using release with this update?)

Yes.

**Review by erezrokah — APPROVED** [review]

**Review by hermanschaaf — COMMENTED** [review]
Nice 💪

**Comment by erezrokah** [comment]
Follow up question, do we need the memory checks we have in the some of the tests https://github.com/cloudquery/plugin-sdk/blob/a61f34ec34e8ec7c3b7663f09b76843d2529e099/types/inet_test.go#L21 if we use the Go allocator?

**Pull request merged**
