### PR TITLE
fix: Skip fields that have "-" json tag

### PR DESCRIPTION
**Pull request by amanenk**
#### Summary

If field has a `json: "-"` tag that means that it is not the data parsed from api. so such a field should be skipped.

---

Use the following steps to ensure your PR is ready to be reviewed

- [ ] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [ ] Run `go fmt` to format your code 🖊
- [ ] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [ ] Update or add tests 🧪
- [ ] Ensure the status checks below are successful ✅

### CODE REVIEW

**Comment by erezrokah** [comment]
Thanks @amanenk 👍 Can you share an example struct with this use case? It will make it easier to understand the reasoning behind the PR

**Comment by candiduslynx** [comment]
> Thanks @amanenk 👍 Can you share an example struct with this use case? It will make it easier to understand the reasoning behind the PR

from https://pkg.go.dev/encoding/json
> As a special case, if the field tag is "-", the field is always omitted. Note that a field with name "-" can still be generated using the tag "-,".
I suppose, we don't need this special case unless someone specifically asks for it, so the default behavior of masking/skipping such fields is better IMO.

See https://pkg.go.dev/google.golang.org/api@v0.96.0/dns/v1#ManagedZone for example (notice the last fields that are of use only to SDK).

**Comment by erezrokah** [comment]
Thanks @candiduslynx that makes sense 🚀

**Review by erezrokah — APPROVED** [review]

**Review by hermanschaaf — APPROVED** [review]

**Comment by hermanschaaf** [comment]
@amanenk Could we please add a test case for this before merging?

**Pull request merged**
