### PR TITLE
chore(go): Rename `interface{}` to `any` for readability

### PR DESCRIPTION
**Pull request by candiduslynx**
#### Summary

`any` is an alias to `interface{}` introduced in Go 1.18. It's shorter and using it instead of `interface{}` improves readability a lot.

Marking this PR as a chore, as the functionality is left intact.

---

Use the following steps to ensure your PR is ready to be reviewed

- [x] Read the [contribution guidelines](../blob/main/CONTRIBUTING.md) 🧑‍🎓
- [x] Run `go fmt` to format your code 🖊
- [x] Lint your changes via `golangci-lint run` 🚨 (install golangci-lint [here](https://golangci-lint.run/usage/install/#local-installation))
- [x] Update or add tests 🧪
- [x] Ensure the status checks below are successful ✅

### CODE REVIEW

**Review by erezrokah — APPROVED** [review]
This looks good to me, but maybe we should have a lint rule for it?

**Comment by candiduslynx** [comment]
They are interchangeable. Also gen code (see `..._pb.go`) sticks to `interface{}` for backward compatibility. I don't think we need a lint rule here.

**Comment by erezrokah** [comment]
> I don't think we need a lint rule here.

I mean if we chose one or the other (mostly for style I think) we should enforce it so our codebase is consistent.
It doesn't have to be in this PR, but maybe open an issue for it? Otherwise I can see someone re-adding `interface{}`

**Comment by candiduslynx** [comment]
@erezrokah 
I've just added the lint config t check for this.
if you have troubles on Mac with this, install `diffutils` via Brew

**Review by hermanschaaf — APPROVED** [review]

**Review by yevgenypats — APPROVED** [review]

**Pull request merged**
