### PR TITLE
feat(writers): More unimplemented writer helpers

### PR DESCRIPTION
**Pull request by disq**
Just to get the other two in parity with streamingbatchwriter helpers, plus tests to make sure the interfaces are satisfied.

### CODE REVIEW

**Comment by yevgenypats** [comment]
In which cases this is used?

**Comment by disq** [comment]
> In which cases this is used?

This can be used in some of the schemaless destinations to get rid of the empty MigrateTable implementations.

**Review by yevgenypats — APPROVED** [review]

**Comment by yevgenypats** [comment]
Shouldn't they though return an error instead of `nil` if not implemented. For example in BigQuery I need to return an error on `DeleteStale`

**Comment by disq** [comment]
> Shouldn't they though return an error instead of `nil` if not implemented. For example in BigQuery I need to return an error on `DeleteStale`

These are to 'ignore' the messages, but I think DeleteStale should return an error, but not MigrateTable? But I don't like the potential disparity between those two as both are 'Unimplemented*' and one returns an error and the other ignores it.

**Comment by disq** [comment]
Maybe we should name them `UnimplementedDeleteStale` vs. `IgnoreMigrateTable`? @yevgenypats

**Comment by yevgenypats** [comment]
> Maybe we should name them `UnimplementedDeleteStale` vs. `IgnoreMigrateTable`? @yevgenypats

Yeah that seems like a good option.

**Pull request merged**
