### PR TITLE
chore: Fix tests/races

### PR DESCRIPTION
**Pull request by disq**
Zerolog ~(Mac only???)~ testwriter issue: https://github.com/cloudquery/plugin-sdk/actions/runs/7350939011/job/20013680798?pr=1437
Flakey test on usage: https://github.com/cloudquery/plugin-sdk/actions/runs/7351363762/job/20014584046?pr=1437

Doesn't really 'fix' the zerolog cancellation testwriter case but circumvents it.

I've tried doing the `logger.With().Logger()` dance all over the schedulers (for every goroutine) to no effect.

### CODE REVIEW

**Comment by hermanschaaf** [comment]
@disq Do you have a link to the error that happened?

**Comment by disq** [comment]
@hermanschaaf Lost the link (we had some in GH actions) but a copy of `go test -tags=assert -race -count=100 ./...` is below.


```
==================
WARNING: DATA RACE
Read at 0x00c000c40043 by goroutine 2009:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:1011 +0x7c
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:1004 +0x70
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:1045 +0x50
  testing.(*T).Log()
      <autogenerated>:1 +0x4c
  github.com/rs/zerolog.TestWriter.Write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:144 +0x154
  github.com/rs/zerolog.(*TestWriter).Write()
      <autogenerated>:1 +0x64
  github.com/rs/zerolog.levelWriterAdapter.WriteLevel()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:25 +0x64
  github.com/rs/zerolog.(*levelWriterAdapter).WriteLevel()
      <autogenerated>:1 +0x20
  github.com/rs/zerolog.(*Event).write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:78 +0x254
  github.com/rs/zerolog.(*Event).msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:149 +0x318
  github.com/rs/zerolog.(*Event).Msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:108 +0x964
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveTableDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:121 +0x8dc
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncRoundRobin.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_round_robin.go:49 +0x134

Previous write at 0x00c000c40043 by goroutine 2006:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1582 +0x56c
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x34
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40

Goroutine 2009 (running) created at:
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncRoundRobin()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_round_robin.go:42 +0x498
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*Scheduler).Sync.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler.go:204 +0xd4

Goroutine 2006 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x5d8
  github.com/cloudquery/plugin-sdk/v4/scheduler.TestScheduler_Cancellation()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_test.go:282 +0x180
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40
==================
--- FAIL: TestScheduler_Cancellation (0.01s)
    writer.go:144: {"level":"info","table":"test_table_success","client":"test","resources":5,"errors":0,"message":"table sync finished"}
    testing.go:1465: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c000702ba3 by goroutine 2128:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:1017 +0x360
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:1004 +0x70
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:1045 +0x50
  testing.(*T).Log()
      <autogenerated>:1 +0x4c
  github.com/rs/zerolog.TestWriter.Write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:144 +0x154
  github.com/rs/zerolog.(*TestWriter).Write()
      <autogenerated>:1 +0x64
  github.com/rs/zerolog.levelWriterAdapter.WriteLevel()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:25 +0x64
  github.com/rs/zerolog.(*levelWriterAdapter).WriteLevel()
      <autogenerated>:1 +0x20
  github.com/rs/zerolog.(*Event).write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:78 +0x254
  github.com/rs/zerolog.(*Event).msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:149 +0x318
  github.com/rs/zerolog.(*Event).Msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:108 +0x624
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveResourcesDfs.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:142 +0x5ec

Previous write at 0x00c000702ba3 by goroutine 1781:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1582 +0x56c
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x34
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40

Goroutine 2128 (running) created at:
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveResourcesDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:132 +0x260
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveTableDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:116 +0x8c0
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncShuffle.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_shuffle.go:57 +0x134

Goroutine 1781 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x5d8
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:2054 +0x80
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.runTests()
      /usr/local/go/src/testing/testing.go:2052 +0x6d8
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1925 +0x908
  main.main()
      _testmain.go:57 +0x294
==================
--- FAIL: TestStrategy_JSONSchema (0.00s)
    testing.go:1465: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c000d50383 by goroutine 32717:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:1011 +0x7c
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:1004 +0x70
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:1045 +0x50
  testing.(*T).Log()
      <autogenerated>:1 +0x4c
  github.com/rs/zerolog.TestWriter.Write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:144 +0x154
  github.com/rs/zerolog.(*TestWriter).Write()
      <autogenerated>:1 +0x64
  github.com/rs/zerolog.levelWriterAdapter.WriteLevel()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:25 +0x64
  github.com/rs/zerolog.(*levelWriterAdapter).WriteLevel()
      <autogenerated>:1 +0x20
  github.com/rs/zerolog.(*Event).write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:78 +0x254
  github.com/rs/zerolog.(*Event).msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:149 +0x318
  github.com/rs/zerolog.(*Event).Msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:108 +0x964
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveTableDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:121 +0x8dc
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncDfs.func2()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:66 +0x144

Previous write at 0x00c000d50383 by goroutine 32714:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1582 +0x56c
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x34
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40

Goroutine 32717 (running) created at:
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:61 +0x4dc
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*Scheduler).Sync.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler.go:202 +0xec

Goroutine 32714 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x5d8
  github.com/cloudquery/plugin-sdk/v4/scheduler.TestScheduler_Cancellation()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_test.go:282 +0x180
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40
==================
--- FAIL: TestScheduler_Cancellation (0.01s)
    writer.go:144: {"level":"info","table":"test_table_success","client":"test","resources":5,"errors":0,"message":"table sync finished"}
    testing.go:1465: race detected during execution of test
==================
WARNING: DATA RACE
Read at 0x00c000f17223 by goroutine 39325:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:1011 +0x7c
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:1004 +0x70
  testing.(*common).Log()
      /usr/local/go/src/testing/testing.go:1045 +0x50
  testing.(*T).Log()
      <autogenerated>:1 +0x4c
  github.com/rs/zerolog.TestWriter.Write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:144 +0x154
  github.com/rs/zerolog.(*TestWriter).Write()
      <autogenerated>:1 +0x64
  github.com/rs/zerolog.levelWriterAdapter.WriteLevel()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/writer.go:25 +0x64
  github.com/rs/zerolog.(*levelWriterAdapter).WriteLevel()
      <autogenerated>:1 +0x20
  github.com/rs/zerolog.(*Event).write()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:78 +0x254
  github.com/rs/zerolog.(*Event).msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:149 +0x318
  github.com/rs/zerolog.(*Event).Msg()
      /Users/disq/go/pkg/mod/github.com/rs/zerolog@v1.29.1/event.go:108 +0x964
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).resolveTableDfs()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_dfs.go:121 +0x8dc
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncShuffle.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_shuffle.go:57 +0x134

Previous write at 0x00c000f17223 by goroutine 39322:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1582 +0x56c
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:477 +0x34
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40

Goroutine 39325 (running) created at:
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*syncClient).syncShuffle()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_shuffle.go:50 +0x570
  github.com/cloudquery/plugin-sdk/v4/scheduler.(*Scheduler).Sync.func1()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler.go:206 +0xbc

Goroutine 39322 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1648 +0x5d8
  github.com/cloudquery/plugin-sdk/v4/scheduler.TestScheduler_Cancellation()
      /Users/disq/go/src/github.com/cloudquery/plugin-sdk/scheduler/scheduler_test.go:282 +0x180
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1595 +0x194
  testing.(*T).Run.func1()
      /usr/local/go/src/testing/testing.go:1648 +0x40
==================
--- FAIL: TestScheduler_Cancellation (0.01s)
    writer.go:144: {"level":"info","table":"test_table_success","client":"test","resources":5,"errors":0,"message":"table sync finished"}
    writer.go:144: {"level":"info","table":"test_table_success","client":"test","resources":5,"errors":0,"message":"table sync finished"}
    testing.go:1465: race detected during execution of test
FAIL
FAIL	github.com/cloudquery/plugin-sdk/v4/scheduler	1.604s
FAIL
```

**Comment by disq** [comment]
@hermanschaaf Link is at https://github.com/cloudquery/plugin-sdk/actions/runs/7350939011/job/20013680798?pr=1437

**Review by hermanschaaf — APPROVED** [review]
Approving so builds can pass; we should probably spend some time trying to find & fix the root cause at some point though

**Pull request merged**
